# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial(6b7c7bac-07fd-420c-a9a5-a812d4f67717)'
    subscriptionId: '6b7c7bac-07fd-420c-a9a5-a812d4f67717'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'java-spring-boot-sree_group'
    location: 'South India'
    templateLocation: 'URL of the file'
    deploymentMode: 'Incremental'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
